Repository CommerceWeavers/SyliusTpayPlugin, pull requests merged in 2024-10, with the labels that each got.

#44 Add displaying the waiting for a payment page
  assets/shop/entrypoint.js
  assets/shop/img/hourglass.gif
  config/config.php
  config/routes_shop.php
  config/routes_webhook.php
  config/services/controller.php
  config/services/payum/action.php
  src/Controller/DisplayWaitingForPaymentPage.php
  src/Payum/Action/ResolveNextRouteAction.php
  src/Route.php
  templates/shop/cart/complete/waiting_for_payment.html.twig
  tests/Application/config/routes/commerce_weavers_tpay.yaml
  tests/E2E/Checkout/TpayPaymentCheckoutTest.php
  tests/Unit/Payum/Action/GetStatusActionTest.php
  tests/Unit/Payum/Action/RefundActionTest.php
  tests/Unit/Payum/Action/ResolveNextRouteActionTest.php
  translations/messages.en.yaml
  translations/messages.pl.yaml
Labels: enhancement

#43 Implement JWS signature validation
  composer.json
  config/config.php
  config/routes_shop.php
  config/routes_webhook.php
  config/services/controller.php
  config/services/form.php
  config/services/payum/action.php
  config/services/payum/factory.php
  config/services/tpay.php
  phpstan.neon
  src/Controller/DisplayWaitingForPaymentPage.php
  src/Controller/PaymentNotificationAction.php
  src/Form/EventListener/PreventSavingEmptyPasswordFieldsListener.php
  src/Form/Type/TpayGatewayConfigurationType.php
  src/Payum/Action/Api/BaseApiAwareAction.php
  src/Payum/Action/Api/NotifyAction.php
  src/Payum/Action/ResolveNextRouteAction.php
  src/Payum/Factory/NotifyDataFactory.php
  src/Payum/Factory/NotifyDataFactoryInterface.php
  src/Payum/Factory/NotifyFactory.php
  src/Payum/Factory/NotifyFactoryInterface.php
  src/Payum/Factory/TpayGatewayFactory.php
  src/Payum/Request/Api/Notify.php
  src/Payum/Request/Api/Notify/NotifyData.php
  src/Routing.php
  src/Test/Payum/Factory/TestTpayGatewayFactory.php
  src/Tpay/Security/Notification/Factory/BasicPaymentFactory.php
  src/Tpay/Security/Notification/Factory/BasicPaymentFactoryInterface.php
  src/Tpay/Security/Notification/Factory/X509Factory.php
  src/Tpay/Security/Notification/Factory/X509FactoryInterface.php
  src/Tpay/Security/Notification/Resolver/CachedCertificateResolver.php
  src/Tpay/Security/Notification/Resolver/CachedTrustedCertificateResolver.php
  src/Tpay/Security/Notification/Resolver/CertificateResolver.php
  src/Tpay/Security/Notification/Resolver/CertificateResolverInterface.php
  src/Tpay/Security/Notification/Resolver/TrustedCertificateResolver.php
  src/Tpay/Security/Notification/Resolver/TrustedCertificateResolverInterface.php
  src/Tpay/Security/Notification/Verifier/ChecksumVerifier.php
  src/Tpay/Security/Notification/Verifier/ChecksumVerifierInterface.php
  src/Tpay/Security/Notification/Verifier/Exception/InvalidSignatureException.php
  src/Tpay/Security/Notification/Verifier/SignatureVerifier.php
  src/Tpay/Security/Notification/Verifier/SignatureVerifierInterface.php
  src/Tpay/TpayApi.php
  tests/Unit/Form/EventListener/PreventSavingEmptyClientSecretListenerTest.php
  tests/Unit/Form/EventListener/PreventSavingEmptyPasswordFieldsListenerTest.php
  tests/Unit/Payum/Action/Api/CreateBlik0TransactionActionTest.php
  tests/Unit/Payum/Action/Api/CreateCardTransactionActionTest.php
  tests/Unit/Payum/Action/Api/CreateRedirectBasedTransactionActionTest.php
  tests/Unit/Payum/Action/Api/NotifyActionTest.php
  tests/Unit/Payum/Action/Api/PayWithCardActionTest.php
  tests/Unit/Payum/Action/RefundActionTest.php
  tests/Unit/Payum/Action/ResolveNextRouteActionTest.php
  tests/Unit/Payum/Factory/NotifyDataFactoryTest.php
  tests/Unit/Tpay/Security/Notification/Factory/BasicPaymentFactoryTest.php
  tests/Unit/Tpay/Security/Notification/Factory/X509FactoryTest.php
  tests/Unit/Tpay/Security/Notification/Resolver/CachedCertificateResolverTest.php
  tests/Unit/Tpay/Security/Notification/Resolver/CachedTrustedCertificateResolverTest.php
  tests/Unit/Tpay/Security/Notification/Verifier/ChecksumVerifierTest.php
  tests/Unit/Tpay/Security/Notification/Verifier/SignatureVerifierTest.php
  translations/messages.en.yaml
  translations/messages.pl.yaml
Labels: enhancement

#55 BLIK payments improvements
  config/services/payum/action.php
  config/services/tpay.php
  src/Form/Type/TpayPaymentDetailsType.php
  src/Payum/Action/Api/CreateBlikLevelZeroTransactionAction.php
  src/Tpay/Factory/CreateBlikLevelZeroPaymentPayloadFactory.php
  src/Tpay/Factory/CreateBlikLevelZeroPaymentPayloadFactoryInterface.php
  tests/Unit/Payum/Action/Api/CreateBlikLevelZeroTransactionActionTest.php
  tests/Unit/Payum/Action/CaptureActionTest.php
Labels: ui

#76 Unify services names
  config/api_resources/order.yaml
  config/config.php
  config/config/framework.php
  config/config/messenger.php
  config/config/sylius_template_events.php
  config/config/webpack_encore.php
  config/config/winzou_state_machine.php
  config/serialization/Pay.xml
  config/serialization/PayResult.xml
  config/services.php
  config/services/api/command.php
  config/services/api/context_builder.php
  config/services/api/doctrine.php
  config/services/api/factory.php
  config/services/api/validator.php
  config/services/context_provider.php
  config/services/controller.php
  config/services/fixtures.php
  config/services/form.php
  config/services/payum/action.php
  config/services/payum/factory.php
  config/services/refunding.php
  config/services/tpay.php
  config/validation/Pay.xml
  index.js
  src/Routing.php
  src/Tpay/Resolver/CachedTpayTransactionChannelResolver.php
  src/Tpay/Security/Notification/Resolver/CachedCertificateResolver.php
  src/Tpay/Security/Notification/Resolver/CachedTrustedCertificateResolver.php
  templates/shop/cart/complete/waiting_for_payment.html.twig
  templates/shop/scripts.html.twig
  templates/shop/styles.html.twig
  tests/Application/config/routes/commerce_weavers_tpay.yaml
  tests/Unit/Payum/Action/ResolveNextRouteActionTest.php
  tests/Unit/Tpay/Security/Notification/Resolver/CachedCertificateResolverTest.php
  tests/Unit/Tpay/Security/Notification/Resolver/CachedTrustedCertificateResolverTest.php
Labels: enhancement, dx

#77 Provide translatable description for TPay call
  config/services/tpay.php
  src/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactory.php
  tests/Unit/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactoryTest.php
  translations/messages.en.yaml
  translations/messages.pl.yaml
Labels: enhancement, ui

#74 Card payments improvements
  assets/shop/entrypoint.js
  assets/shop/js/card_encoder.js
  assets/shop/js/card_form.js
  src/Form/Type/TpayCardType.php
  src/Form/Type/TpayGatewayConfigurationType.php
  src/Payum/Action/Api/PayWithCardAction.php
  src/Payum/Action/GetStatusAction.php
  src/Tpay/Factory/CreateBlikLevelZeroPaymentPayloadFactory.php
  src/Tpay/Factory/CreateCardPaymentPayloadFactory.php
  src/Tpay/PayGroup.php
  src/Tpay/PaymentType.php
  templates/shop/cart/complete/_card.html.twig
  translations/messages.en.yaml
  translations/messages.pl.yaml
  translations/validators.en.yaml
  translations/validators.pl.yaml
Labels: enhancement, ui

#79 Handle a failing payment case
  config/config.php
  config/routes_shop.php
  config/services.php
  config/services/controller.php
  config/services/payment.php
  config/services/tpay.php
  config/services/tpay/routing.php
  phpstan.neon
  src/Controller/DisplayPaymentFailedPageAction.php
  src/Controller/DisplayThankYouPageAction.php
  src/Controller/RetryPaymentAction.php
  src/Payment/Canceller/PaymentCanceller.php
  src/Payment/Canceller/PaymentCancellerInterface.php
  src/Payment/Checker/PaymentCancellationPossibilityChecker.php
  src/Payment/Checker/PaymentCancellationPossibilityCheckerInterface.php
  src/Payment/Exception/PaymentCannotBeCancelledException.php
  src/Payum/Action/ResolveNextRouteAction.php
  src/Routing.php
  src/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactory.php
  src/Tpay/Routing/Generator/CallbackUrlGenerator.php
  src/Tpay/Routing/Generator/CallbackUrlGeneratorInterface.php
  templates/shop/cart/complete/payment_failed.html.twig
  tests/Api/Utils/OrderPlacerTrait.php
  tests/E2E/Helper/Order/RetryPaymentTrait.php
  tests/E2E/RetryPayment/RetryingPaymentTest.php
  tests/Unit/Payment/Canceller/PaymentCancellerTest.php
  tests/Unit/Payment/Checker/PaymentCancellationPossibilityCheckerTest.php
  tests/Unit/Payum/Action/ResolveNextRouteActionTest.php
  tests/Unit/Tpay/Factory/CreateRedirectBasedPaymentPayloadFactoryTest.php
  tests/Unit/Tpay/Routing/Generator/CallbackUrlGeneratorTest.php
  translations/flashes.en.yaml
  translations/flashes.pl.yaml
  translations/messages.en.yaml
  translations/messages.pl.yaml
Labels: ui

#81 Allow cancelling in-progress payments using API
  config/api_resources/order.yaml
  config/config/api_platform.php
  config/config/messenger.php
  config/services/api/command.php
  config/services/controller.php
  src/Api/Doctrine/QueryItemExtension/OrderShopUserItemExtension.php
  src/Api/Doctrine/QueryItemExtension/OrderVisitorItemExtension.php
  src/Command/CancelLastPayment.php
  src/Command/CancelLastPaymentHandler.php
  src/Controller/RetryPaymentAction.php
  tests/Api/DataFixtures/shop/cancelling_payment/cart.yml
  tests/Api/DataFixtures/shop/cancelling_payment/channel.yml
  tests/Api/DataFixtures/shop/cancelling_payment/payment_method.yml
  tests/Api/DataFixtures/shop/cancelling_payment/shipping_method.yml
  tests/Api/JsonApiTestCase.php
  tests/Api/Shop/CancellingPaymentTest.php
  tests/E2E/RetryPayment/RetryingPaymentTest.php
  tests/Unit/Command/CancelLastPaymentHandlerTest.php
Labels: api

#97 Add support for Apple Pay payments in UI
  .gitignore
  assets/shop/checkout_complete_entrypoint.js
  assets/shop/js/apple_pay.js
  assets/shop/order_show_entrypoint.js
  assets/shop/scss/style.scss
  config/config.php
  config/config/sylius_fixtures.php
  config/config/sylius_template_events.php
  config/routes_webhook.php
  config/services/controller.php
  config/services/payum/action.php
  config/services/tpay.php
  phpunit.xml.dist
  src/Controller/InitApplePayPaymentAction.php
  src/Form/Type/TpayGatewayConfigurationType.php
  src/Form/Type/TpayPaymentDetailsType.php
  src/Payum/Action/Api/InitializeApplePayPaymentAction.php
  src/Payum/Request/Api/InitializeApplePayPayment.php
  src/Routing.php
  src/Tpay/ApplePayApi.php
  src/Tpay/Factory/CreateInitializeApplePayPaymentPayloadFactory.php
  src/Tpay/Factory/CreateInitializeApplePayPaymentPayloadFactoryInterface.php
  src/Tpay/Model/Field/DisplayName.php
  src/Tpay/Model/Field/DomainName.php
  src/Tpay/Model/Field/ValidationUrl.php
  src/Tpay/Model/RequestBody/InitApplePay.php
  src/Tpay/PayGroup.php
  src/Tpay/TpayApi.php
  src/Twig/TpayExtension.php
  src/Twig/TpayRuntime.php
  templates/bundles/SyliusShopBundle/Checkout/Complete/_navigation.html.twig
  templates/shop/cart/complete/_apple_pay.html.twig
  templates/shop/cart/complete/_google_pay.html.twig
  tests/Api/DataFixtures/shop/paying_for_orders_by_apple_pay.yml
  tests/Application/.env
  tests/Application/.env.dev
  tests/Application/config/routes.yaml
  tests/Application/public/.well-known/apple-developer-merchantid-domain-association
  tests/Application/templates/apple_pay_demo.html.twig
  tests/Unit/Payum/Action/Api/InitializeApplePayPaymentActionTest.php
  tests/Unit/Tpay/Factory/CreateApplePayPaymentPayloadFactoryTest.php
  tests/Unit/Tpay/Factory/CreateInitializeApplePayPaymentPayloadFactoryTest.php
  tests/Unit/Twig/TpayRuntimeTest.php
  tests/mockoon_tpay.json
  translations/messages.en.yaml
  translations/messages.pl.yaml
Labels: enhancement, ui
